export const ABOUT = {
  intro: [
    'Soy Víctor, Product Designer.',
    'Diseño producto B2B donde un error operativo cuesta dinero.',
    'Informático de formación, Product Designer de oficio. Nueve años.',
  ],
  cities: [
    { name: 'Cumaná', country: 'VE' as const },
    { name: 'Caracas', country: 'VE' as const },
    { name: 'Zulia', country: 'VE' as const },
    { name: 'Jaén', country: 'ES' as const },
    { name: 'Madrid', country: 'ES' as const },
    { name: 'Lleida', country: 'ES' as const },
    { name: 'Barcelona', country: 'ES' as const },
    { name: 'Málaga', country: 'ES' as const, years: '2022 – ahora', current: true },
  ],
  places: [] as { src: string; alt: string; caption: string }[],
  education: [
    { degree: 'Licenciatura en Informática', school: 'Universidad de Oriente', place: 'Cumaná, Venezuela', years: '2006–2017' },
  ],
  ikigai: {
    tech: 'Informático de formación: sé cómo se construye lo que diseño, y respeto cómo piensa el framework.',
    design: 'Product Designer de oficio: nueve años en producto B2B denso, de la arquitectura al handoff.',
    business: 'Reglas de negocio, discovery con Product Owners y decisiones defendidas en lenguaje de negocio.',
    center: 'Product design',
  },
  companies: [
    { id: 'atrinium', name: 'Atrinium', years: '2022–2026', href: '/casos/hermes',
      body: 'Único diseñador de un holding con cinco productos. El principal, HERMES: un ERP SaaS multi-tenant para aseguradoras, reaseguradoras, MGAs y brokers, con el administrador que gobierna todo el grupo. Alrededor, facturación electrónica, un sistema de pólizas 360, gestión de usuarios y permisos y un e-commerce. Cinco productos, un solo lenguaje de diseño.' },
    { id: 'mercantil', name: 'Mercantil Panamá', years: '2020–2022', href: '/?f=banca#trabajo',
      body: 'Banca digital en entorno regulado. El sistema ya existía y mi trabajo era aplicarlo con criterio y validar cada pantalla antes de desarrollo: tests no moderados con Maze, entrevistas propias y sesiones con Marketing para los emails transaccionales. Nada pasaba a desarrollo sin haberse probado.' },
    { id: 'taksio', name: 'Taksio', years: '2017–2019', href: '/?f=transporte#trabajo',
      body: 'Plataforma de movilidad multimodal en Caracas: design system y flujos operativos de conductor y pasajero levantados desde cero.' },
  ],
  vision: {
    title: 'Diseño sistemas, no pantallas.',
    paragraphs: [
      'Mi base en informática no está para escribir código de producción: está para pensar el producto en sistemas, en estructura y en cómo se va a construir de verdad. Modelo el dominio antes que la pantalla, defino estados, reglas y casos límite, y cierro con un handoff que el equipo puede construir sin interpretar nada.',
      'Trabajo con patrones validados y criterios de usabilidad, no con invenciones, y respetando cómo se construye realmente en React, Chakra UI o Tailwind. Esta web es un ejemplo: el diseño es mío y dirigí la implementación con IA hasta el detalle. Generar es la parte fácil; lo que aporto es saber qué hay que pedir y reconocer cuándo lo que devuelve no sirve.',
      'Me interesan los flujos completos, no las pantallas sueltas. Sistemas que hagan que el siguiente diseño y el siguiente desarrollo cuesten menos que el anterior.',
    ],
  },
  skills: [
    'Arquitectura de información y flujos críticos en dominios regulados',
    'Design systems con gobernanza y criterios de uso',
    'Producto multi-tenant y white-labeling',
    'Formularios y reglas de negocio declarados como dato',
    'Accesibilidad WCAG 2.2 como requisito de entrada',
    'Discovery y defensa de propuestas ante Product Owners',
    'Handoff acompañado y diálogo técnico con desarrollo',
    'Research por observación indirecta cuando no hay acceso a usuarios',
  ],
  bio: [
  'Diseño producto B2B donde un error operativo cuesta dinero.',
  '*Informático de formación, Product Designer de oficio. Nueve años.* Esa base no está para escribir código de producción: está para cómo pienso el producto, *en sistemas, en estructura y en cómo se va a construir esto de verdad*. Diseño, *planteo la arquitectura de la solución* y la llevo hasta algo que funciona: *modelo el dominio antes que la pantalla*, *defino estados, reglas y casos límite*, y cierro con un *handoff que el equipo puede construir sin interpretar nada*. Trabajo con *patrones validados y criterios de usabilidad*, no con invenciones, y respetando cómo se construye realmente en *React, Chakra UI o Tailwind*. Saber cómo piensa el framework es lo que hace que un diseño llegue a producción tal como se diseñó. Esta web es un ejemplo: el diseño es mío, la implementación *la generé con IA y la dirigí hasta el detalle*. Generar es la parte fácil; lo que aporto es *saber qué hay que pedir y reconocer cuándo lo que devuelve no sirve*.',
  'Entre 2022 y 2026 fui *el único diseñador de un holding con cinco productos*. El principal, un *ERP SaaS multi-tenant para aseguradoras, reaseguradoras, MGAs y brokers*: suscripción, pólizas, recibos, facturación y siniestros. Con él, *el módulo administrador que gobierna todo el grupo*: tenants, planes, permisos y configuración por cliente.',
  'Alrededor de ese núcleo diseñé el resto de la cartera. *Facturación electrónica* con dos audiencias opuestas: el asesor que factura a diario y necesita velocidad, y el cliente final que entra una vez al mes y necesita contexto. Un *sistema de pólizas 360* donde una sola vista sostiene equipo, pólizas, recibos y los pagos a cada interesado. La *gestión de usuarios y permisos* que cruza los cinco productos. Y un *e-commerce* como línea alternativa. *Cinco productos, un solo lenguaje de diseño.*',
  'Es *producto B2B denso*: *tablas de alta densidad*, *wizards de varios pasos*, *formularios generados por esquema*, *white-labeling por tenant* y *reglas de negocio que cambian según el contrato*. Nada de eso se resuelve pantalla a pantalla.',
  'Al entrar, cada módulo se había construido con criterios distintos. La respuesta obvia era imponer un sistema único; propuse otra: *el nivel de sistema que cada producto se puede permitir*. *Design system completo* para el ERP y el administrador: componentes, tokens, jerarquía tipográfica y, sobre todo, *las reglas de decisión: cuándo se usa cada patrón y por qué*. En los productos ligeros, *brandsheet y UI kit*, lo suficiente para sostener la coherencia sin cargarlos con una gobernanza que no necesitan. El punto de partida fue una *auditoría del monorepo*: *267 valores de color reducidos a 24 tokens* con un rol asignado cada uno, *adoptados por los cuatro desarrolladores front*. Sin esa base compartida, reutilizar componentes entre productos no ahorra nada. Es lo que hace que cinco negocios distintos no se sientan como cinco empresas distintas.',
  'Cada semana me senté con *los Product Owners de las aseguradoras*: *discovery antes de diseñar*, y defender cada propuesta antes de pasarla a desarrollo. Se aprende rápido a *explicar una decisión de diseño en lenguaje de negocio*.',
  'Antes, *banca digital en entorno regulado*. Allí el sistema ya existía y mi trabajo era otro: *aplicarlo con criterio* y *validar cada pantalla antes de que llegara a desarrollo*. *Tests de usabilidad no moderados con Maze* y *entrevistas propias* para entender el porqué detrás de la métrica, no solo el dónde. También *sesiones con Marketing para testear los emails transaccionales* y las piezas de marca fuera de la app, porque la experiencia no termina en la pantalla del producto. Nada pasaba a desarrollo sin haberse probado. Antes de eso, una *plataforma de movilidad multimodal*: *design system y flujos operativos levantados desde cero*.',
  'Me interesan *los flujos completos, no las pantallas sueltas*. *Sistemas que hagan que el siguiente diseño y el siguiente desarrollo cuesten menos que el anterior.*',
  ],
  tools: ['Figma', 'FigJam', 'Prototipado interactivo', 'Chakra UI', 'Tailwind', 'React', 'GitHub', 'Vercel', 'Microsoft Clarity', 'Google Analytics', 'Maze', 'Mobbin', 'Claude'],
};
